-- =============== DATABASE & SCHEMA ================
SHOW DATABASES; 
-- ECOMMERCE_DB

SHOW TABLES IN DATABASE ECOMMERCE_DB;

SHOW SCHEMAS;
-- ANALYTICS

SHOW SCHEMAS IN DATABASE ECOMMERCE_DB;

-- ================ AVAILABLE TABLES =================
SELECT * FROM ECOMMERCE_DB.ANALYTICS.CUSTOMERS_STG;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.CUSTOMERS;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.TRANSACTIONS_STG;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.TRANSACTIONS;
-- ====================================================

-- ================ TABLES STRUCTURE =================
DESC TABLE ECOMMERCE_DB.ANALYTICS.CUSTOMERS_STG;
-- ID VARCHAR(20)
-- NAME VARCHAR(20)
-- AGE NUMBER(38,0)
-- GENDER VARCHAR(20)
-- STATE VARCHAR(100)
-- SIGNUP_DATE DATE
-- EMAIL VARCHAR(255)
-- PHONE_NUMBER VARCHAR(30)
-- SUBSCRIBE VARCHAR(10)

DESC TABLE ECOMMERCE_DB.ANALYTICS.CUSTOMERS;
-- ID VARCHAR(20)
-- NAME VARCHAR(20)
-- AGE NUMBER(38,0)
-- GENDER VARCHAR(20)
-- STATE VARCHAR(100)
-- SIGNUP_DATE DATE
-- EMAIL VARCHAR(255)
-- PHONE_NUMBER VARCHAR(30)
-- SUBSCRIBE VARCHAR(10)
-- INSERTED_AT TIMESTAMP_TZ(9)
-- MODIFIED_AT TIMESTAMP_TZ(9)

DESC TABLE ECOMMERCE_DB.ANALYTICS.TRANSACTIONS_STG;
--  ID VARCHAR(30)
-- CUSTOMER_ID VARCHAR(20)
-- TRANSACTION_DATE DATE
-- PRODUCT_ID VARCHAR(30)
-- QUANTITY NUMBER(38,0)
-- UNIT_PRICE NUMBER(12,2)
-- PAYMENT_METHOD VARCHAR(30)
-- DISCOUNT_APPLIED NUMBER(5,2)
-- TRANSACTION_STATUS VARCHAR(30)
-- REVIEW_TEXT VARCHAR(16777216)
-- GROSS_AMOUNT NUMBER(14,2)
-- DISCOUNT_AMOUNT NUMBER(14,2)
-- NET_AMOUNT NUMBER(14,2)

DESC TABLE ECOMMERCE_DB.ANALYTICS.TRANSACTIONS;
--  ID VARCHAR(30)
-- CUSTOMER_ID VARCHAR(20)
-- TRANSACTION_DATE DATE
-- PRODUCT_ID VARCHAR(30)
-- QUANTITY NUMBER(38,0)
-- UNIT_PRICE NUMBER(12,2)
-- PAYMENT_METHOD VARCHAR(30)
-- DISCOUNT_APPLIED NUMBER(5,2)
-- TRANSACTION_STATUS VARCHAR(30)
-- REVIEW_TEXT VARCHAR(16777216)
-- GROSS_AMOUNT NUMBER(14,2)
-- DISCOUNT_AMOUNT NUMBER(14,2)
-- NET_AMOUNT NUMBER(14,2)
-- INSERTED_AT TIMESTAMP_TZ(9)
-- MODIFIED_AT TIMESTAMP_TZ(9)
-- ====================================================

